// ------------------------------------------------------------------------------
//  <autogenerated>
//      This code was generated by a tool.
//      Mono Runtime Version: 4.0.30319.42000
// 
//      Changes to this file may cause incorrect behavior and will be lost if 
//      the code is regenerated.
//  </autogenerated>
// ------------------------------------------------------------------------------

namespace bBridgeAPISDK.Test {
    using System;
    using System.Reflection;
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class TestResources {
        
        private static System.Resources.ResourceManager resourceMan;
        
        private static System.Globalization.CultureInfo resourceCulture;
        
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal TestResources() {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static System.Resources.ResourceManager ResourceManager {
            get {
                if (object.Equals(null, resourceMan)) {
					System.Resources.ResourceManager temp = new System.Resources.ResourceManager("bBridgeAPISDK.Test.TestResources", typeof(TestResources).GetTypeInfo().Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        internal static string bBridgeAPIBaseURI {
            get {
                return ResourceManager.GetString("bBridgeAPIBaseURI", resourceCulture);
            }
        }
        
        internal static string bBridgeAPIPassword {
            get {
                return ResourceManager.GetString("bBridgeAPIPassword", resourceCulture);
            }
        }
        
        internal static string bBridgeAPIUserName {
            get {
                return ResourceManager.GetString("bBridgeAPIUserName", resourceCulture);
            }
        }
        
        internal static string JWTTokenRegex {
            get {
                return ResourceManager.GetString("JWTTokenRegex", resourceCulture);
            }
        }
        
        internal static string bBridgeAPIAuthUrlSuffix {
            get {
                return ResourceManager.GetString("bBridgeAPIAuthUrlSuffix", resourceCulture);
            }
        }
    }
}
